# version: '3.8'
services:
  ui:
    build: ../${PROJECT_NAME}-ui/
    restart: always
    working_dir: /var/www/${PROJECT_NAME}-ui
    # command: ["bash", "-c", "npm install && npm run dev"]
    environment:
      TZ: Asia/Tokyo
    tty: true
    volumes:
      - ${UI_DIR}:/var/www/${PROJECT_NAME}-ui
      # - nodemodules:/var/www/${PROJECT_NAME}-ui/node_modules
    ports:
      - "3000:3000"
  api:
    build: ../${PROJECT_NAME}-api/
    restart: always
    working_dir: "/var/www/${PROJECT_NAME}-api"
    # command: ["bash", "-c", "go mod download && go mod verify"]
    environment:
      TZ: Asia/Tokyo
    tty: true
    volumes:
      - ${API_DIR}:/var/www/${PROJECT_NAME}-api
    ports:
      - "9090:9090"
    depends_on:
      - mysql
  mysql:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4_unicode_ci
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql:
  nodemodules: